package io.legado.app.ui.compose.platform

/**
 * commonMain 共享字符串表 (jvmMain/iOS 共用, 单一数据源, 避免多副本维护)。
 *
 * 收录所有 i18n key, 值与 app 端 values-zh/strings.xml 默认中文对齐 (zh-CN), 桌面端/iOS 端不做 i18n。
 * 未识别的 key 返回 key 本身 (由调用方 rememberString / jvmGetString 处理)。
 */
val sharedStringTable: Map<String, String> = mapOf(
            "ok" to "确定",
            "cancel" to "取消",
            // 退出未保存确认对话框 (与 app 端 values-zh/strings.xml 对齐)
            "exit" to "退出",
            "exit_no_save" to "尚未保存，是否继续编辑",
            "yes" to "是",
            "no" to "否",
            "reduce" to "减少",
            "plus" to "增加",
            "clear" to "清除",
            "more_menu" to "更多",
            "empty" to "空空如也",
            "revert_selection" to "反选",
            // 书源管理 Screen 用到的 key (与 app 端 values-zh-rCN/strings.xml 对齐)
            "book_source" to "书源",
            "search_book_source" to "搜索书源",
            "sort" to "排序",
            "sort_desc" to "降序",
            "sort_manual" to "手动排序",
            "sort_auto" to "自动排序",
            "sort_by_name" to "按名称",
            "sort_by_url" to "按链接",
            "sort_by_lastUpdateTime" to "按更新时间",
            "sort_by_respondTime" to "按响应时间",
            "is_enabled" to "已启用",
            "menu_action_group" to "分组",
            "group_manage" to "分组管理",
            "enabled" to "启用",
            "disabled" to "禁用",
            "need_login" to "需登录",
            "no_group" to "未分组",
            "error_load_toc" to "加载目录失败", // BookInfoScreen toc 加载失败提示 (与 app 端 values-zh/strings.xml 对齐)
            "load_toc" to "加载目录", // BookInfoScreen 加载目录按钮 (与 app 端 values-zh/strings.xml 对齐)
            "load_info" to "加载详情页", // BookInfoScreen 加载详情页按钮 (与 app 端 values-zh/strings.xml 对齐)
            "enabled_explore" to "启用发现",
            "disabled_explore" to "禁用发现",
            "add_book_source" to "添加书源",
            "import_local" to "本地导入",
            "import_on_line" to "网络导入",
            "group_sources_by_domain" to "按域名分组",
            "help" to "帮助",
            "edit" to "编辑",
            "to_top" to "置顶",
            "to_bottom" to "置底",
            "login" to "登录",
            // SourceLoginDialog 下沉带入 (与 app 端 values-zh/strings.xml 对齐)
            "login_source" to "登录 %s", // rememberString formatArgs 填 bookSourceName
            "login_url" to "登录 URL(loginUrl)",
            "login_header" to "登录请求头",
            "show_login_header" to "查看登录请求头",
            "del_login_header" to "删除登录请求头",
            "login_header_tip" to "请求头", // 输入框 label (避免与按钮文案 "cookie"=清除 Cookie 冲突)
            "cookie_input" to "Cookie", // SourceLoginDialog Cookie 输入框 label (与 "cookie"=清除 Cookie 区分)
            "search" to "搜索",
            "debug" to "调试",
            "delete" to "删除",
            "enable_explore" to "启用发现",
            "disable_explore" to "禁用发现",
            // ImportListScaffold 用到的 key (与 app 端 values-zh/strings.xml 对齐)
            "open" to "打开",
            "select_all_count" to "全选（%1\$d/%2\$d）",
            "select_cancel_count" to "取消全选（%1\$d/%2\$d）",
            // MoreConfigScreen 用到的 key (与 app 端 values-zh/strings.xml 对齐)
            "more_config" to "更多配置",
            "screen_direction" to "屏幕方向",
            "keep_light" to "屏幕超时",
            "pt_hide_status_bar" to "隐藏状态栏",
            "pt_hide_navigation_bar" to "隐藏导航栏",
            "double_page_horizontal" to "平板/横屏双页",
            "progress_bar_behavior" to "进度条行为",
            "use_zh_layout" to "使用自定义中文分行",
            "text_full_justify" to "文字两端对齐",
            "text_bottom_justify" to "文字底部对齐",
            "mouse_wheel_page" to "鼠标滚轮翻页",
            "volume_key_page_on_play" to "朗读时音量键翻页",
            "page_touch_slop_title" to "滑动翻页阈值",
            "auto_change_source" to "自动换源",
            "preview_image_by_click" to "点击预览图片",
            "click_regional_config" to "点击区域设置",
            "custom_page_key" to "自定义翻页按键",
            "show_read_title_addition" to "展示顶部工具栏附加区域",
            // ReadAloudConfigScreen 用到的 key (与 app 端 values-zh/strings.xml 对齐)
            "read_aloud_config" to "朗读配置",
            "aloud_config" to "朗读设置",
            "ignore_audio_focus_title" to "忽略音频焦点",
            "ignore_audio_focus_summary" to "允许与其他应用同时播放音频",
            "pause_read_aloud_while_phone_calls_title" to "来电期间暂停朗读",
            "pause_read_aloud_while_phone_calls_summary" to "在通话期间暂停朗读，需要读取手机状态权限",
            "read_aloud_wake_lock" to "朗读服务唤醒锁",
            "read_aloud_wake_lock_summary" to "开启朗读的时候启用唤醒锁,有些手机开启唤醒锁会被杀后台",
            "system_media_control_compatibility_change" to "系统媒体控件兼容性更改",
            "system_media_control_compatibility_change_summary" to "当锁屏不显示系统媒体控件时可以尝试开启，比如oneui7.0或vivo等",
            "pref_media_button_per_next" to "媒体按钮•上一首|下一首",
            "pref_media_button_per_next_summary" to "上一段|下一段/上一章|下一章",
            "read_aloud_by_page" to "按页朗读",
            "read_aloud_by_page_summary" to "及时翻页，翻页时会停顿一下",
            "stream_read_aloud_audio" to "流式播放音频",
            "stream_read_aloud_audio_summary" to "即边下边播，网络不好时播放会断断续续，仅TTS源有效",
            "speak_engine" to "朗读引擎",
            "system_tts" to "系统 TTS", // 系统默认 TTS 引擎名称 (ReadAloudConfig / TtsControlPanel)
            "sys_tts_config" to "系统 TTS 设置",
            "sys_tts_config_summary" to "打开系统 TTS 设置界面",
            // TocScreen 下沉带入 (与 app 端 values-zh/strings.xml 对齐)
            "chapter_list" to "目录",
            "bookmark" to "书签",
            "export" to "导出",
            "export_md" to "导出(MD)",
            "txt_toc_rule" to "TXT 目录规则",
            "split_long_chapter" to "拆分超长章节",
            "reverse_toc" to "反转目录",
            "use_replace" to "使用替换",
            "load_word_count" to "加载字数",
            "log" to "日志",
            "go_to_top" to "滚动到顶部",
            "go_to_bottom" to "滚动到底部",
            // TipConfigScreen 下沉带入 (与 app 端 values-zh/strings.xml 对齐)
            "tip_config" to "提示信息配置", // 桌面端 TipConfigScreen 包装 title (页眉页脚提示)
            "body_title" to "正文标题",
            "title_left" to "靠左",
            "title_center" to "居中",
            "title_hide" to "隐藏",
            "title_font_size" to "字号",
            "title_margin_top" to "上边距",
            "title_margin_bottom" to "下边距",
            "header" to "页眉",
            "footer" to "页脚",
            // 原 XML 用 CDATA 转义 &, 实际字符串为 "页眉&页脚"
            "header_footer" to "页眉&页脚",
            "show_hide" to "显示/隐藏",
            "left" to "左",
            "middle" to "中",
            "right" to "右",
            "text_color" to "文字颜色",
            "text_bg_style" to "文字颜色和背景（长按自定义）", // TipConfigScreen 文字颜色和背景样式入口 (与 app 端 values-zh/strings.xml 对齐)
            "text" to "文字", // 通用文字 label (与 app 端 values-zh/strings.xml 对齐)
            "tip_divider_color" to "分隔线颜色",
            "show" to "显示",
            "hide" to "隐藏",
            "hide_when_status_bar_show" to "状态栏显示时隐藏",
            // PaddingConfigScreen 下沉带入 (与 app 端 values-zh/strings.xml 对齐)
            "padding_config" to "边距配置",
            "main_body" to "正文",
            "showLine" to "显示分隔线",
            "padding_top" to "上边距",
            "padding_bottom" to "下边距",
            "padding_left" to "左边距",
            "padding_right" to "右边距",
            // EffectiveReplacesScreen 下沉带入 (与 app 端 values-zh/strings.xml 对齐)
            "effective_replaces" to "起效的替换",
            "add" to "添加",
            "close" to "关闭",
            "source_filter_rule_manage" to "管理全部",
            "source_filter_rule_no_match" to "当前范围没有命中的屏蔽规则", // 屏蔽规则列表无命中提示 (与 app 端 values-zh/strings.xml 对齐)
            // FontSelectDialog 下沉带入 (与 app 端 values-zh/strings.xml 对齐)
            "select_font" to "选择字体",
            "default_font" to "默认字体",
            "other_folder" to "其它目录",
            "system_typeface" to "系统内置字体样式",
            // BookshelfComposablesShared 下沉带入 (与 app 端 values-zh/strings.xml 对齐)
            "bookshelf" to "书架",
            "bookshelf_empty" to "书架还空着，先去搜索书籍或从发现里添加吧！",
            "book_local" to "添加本地",
            "add_url" to "添加网址",
            "add_book_url" to "添加书籍网址",
            "force_refresh_book" to "强制更新书籍",
            "select_file" to "选择文件",
            "add_remote_book" to "远程书籍",
            // ReplaceEditScreen / ReplaceRuleListScreen 下沉带入 (与 app 端 values-zh/strings.xml 对齐)
            "replace_rule_edit" to "替换规则编辑",
            "action_save" to "保存",
            "copy_rule" to "拷贝规则",
            "paste_rule" to "粘贴规则",
            "replace_rule_summary" to "替换规则名称",
            "replace_rule" to "替换规则",
            "replace_to" to "替换为",
            "replace_scope" to "替换范围，选填书名或者书源 URL",
            "replace_exclude_scope" to "排除范围，选填书名或者书源 URL",
            "replace_rule_title" to "替换净化",
            "replace_purify" to "替换净化",
            "replace_purify_search" to "替换净化-搜索",
            "replace_enable_default_s" to "新加入书架的书是否启用替换净化",
            "replace_enable_default_t" to "默认启用替换净化",
            "replace" to "替换",
            "scope_title" to "作用于标题",
            "scope_content" to "作用于正文",
            "use_regex" to "使用正则表达式",
            "add_replace_rule" to "新建替换",
            "sure_del" to "是否确认删除？",
            "draw" to "提醒",
            "timeout_millisecond" to "超时毫秒数",
            "respondTime" to "响应时间：%1\$d ms",
            "rule_subscription" to "规则订阅",
            // RSS 源入口 (桌面端独有, MyConfigScreen showRssEntry=true 时渲染)
            "rss_sources" to "RSS",
            "dict_rule" to "字典规则",
            "enable_selection" to "启用所选",
            "disable_selection" to "禁用所选",
            "selection_to_top" to "置顶所选",
            "selection_to_bottom" to "置底所选",
            "export_selection" to "导出所选",
            // BookInfoScreen / BookSourceEditScreen 下沉带入 (与 app 端 values-zh/strings.xml 对齐)
            "book_info" to "书籍信息",
            "book_info_delete_alert_summary" to "删除书籍前弹出确认对话框",
            "book_info_delete_alert_title" to "删除书籍时提醒",
            "book_info_horizontal_layout" to "书籍详情横向布局",
            "book_info_horizontal_layout_summary" to "书籍详情页将封面与信息并排显示",
            "book_intro" to "内容简介",
            "book_name" to "书名",
            "book_source_manage" to "书源管理",
            "book_source_manage_desc" to "新建、导入、编辑或管理书源",
            "book_tree_uri_t" to "书籍保存位置",
            "book_type" to "类型：",
            "bookshelf_cover_height" to "列表模式下封面高度",
            "bookshelf_layout" to "书架布局",
            "bookshelf_management" to "书籍管理",
            "author" to "作者",
            "cookie" to "清除 Cookie",
            "copy_book_url" to "拷贝书籍 URL",
            "copy_source" to "拷贝源",
            "copy_toc_url" to "拷贝目录 URL",
            "debug_source" to "调试源",
            "delete_source" to "删除源",
            "disable_source" to "禁用源",
            // VerificationCodeDialog 下沉带入 (与 app 端 values-zh/strings.xml 对齐)
            "verification_code" to "验证码",
            "captcha_load_failed_hint" to "无法加载验证码图片, 请手动打开:",
            "edit_book_source" to "编辑书源",
            "edit_source" to "编辑源",
            "paste_source" to "粘贴源",
            "like_source" to "赞",
            "not_like_source" to "踩",
            "review" to "评论",
            "share" to "分享",
            "str_share" to "字符串分享",
            "in_favorites" to "已收藏",
            "out_favorites" to "未收藏",
            "favorite" to "收藏",
            "intro_show_null" to "简介：暂无简介",
            "add_to_bookshelf" to "放入书架",
            "remove_from_bookshelf" to "删除书籍",
            // ChangeSourceScreen / SearchScreen / SearchContentScreen 下沉带入 (与 app 端 values-zh/strings.xml 对齐)
            "all_source" to "全部书源",
            "groups_or_source" to "多分组/书源",
            "precision_search" to "精准搜索",
            "screen" to "筛选",
            "search_book_key" to "搜索书名、作者",
            "search_content" to "全文搜索",
            "search_content_size" to "搜索结果",
            "search_layout" to "搜索布局",
            "searchHistory" to "搜索历史",
            "source_filter_rule" to "屏蔽规则",
            "start" to "开始",
            "stop" to "停止",
            "refresh" to "刷新",
            "next_chapter" to "下一章",
            "previous_chapter" to "上一章",
            "read_dur_progress" to "最近：%s",
            "read_record" to "阅读记录",
            "reading" to "阅读",
            // ReadRecordScreen 下沉带入 (与 app 端 values-zh/strings.xml 对齐)
            "read_record_today_total" to "当日 %1\$s / 总 %2\$s",
            "reading_time_sort" to "阅读时长排序",
            "last_read_time_sort" to "阅读时间排序",
            "enable_record" to "开启记录",
            "delete_all" to "删除所有",
            "sure_del_any" to "是否确认删除 %s？",
            "today_read_time" to "今日",
            "month_read_time" to "本月",
            "read_book_count" to "已读书籍数",
            "week_read_time" to "本周",
            "all_read_time" to "总阅读时间",
            "avg_book_read_time" to "均读时长",
            "read_heatmap_title" to "阅读热力图",
            "prev_month" to "上个月",
            "next_month" to "下个月",
            "month_label_format" to "%1\$d 年 %2\$d 月",
            "loading" to "加载中…",
            // CodeDialog 下沉带入 (对齐 app 端 CodeDialog 硬编码标题 "code view")
            "code_view" to "code view",
            "success" to "成功",
            "switchLayout" to "切换布局",
            // BookshelfManageScreen / ImportBookScreen / RemoteBookScreen 下沉带入 (与 app 端 values-zh/strings.xml 对齐)
            "action_download" to "下载",
            "allow_update" to "允许更新",
            "download_to_local" to "下载到本地",
            "empty_msg_import_book" to "点击右上角文件夹图标，选择文件夹",
            "export_all_use_book_source" to "导出所有书的书源",
            "export_config" to "导出文件设置",
            "export_folder" to "导出文件夹",
            "export_to_web_dav" to "导出到 WebDav",
            "custom_export_section" to "自定义Epub导出章节",
            "filter_book_type" to "按类型筛选",
            "import_file_name" to "导入文件名",
            "local_book" to "本地书籍",
            "menu_download_after" to "下载之后章节",
            "menu_download_all" to "下载全部章节",
            "move_to_group" to "移入分组",
            "pre_download" to "预下载",
            "remote_book" to "远程书籍",
            "scan_folder" to "智能扫描",
            "select_folder" to "选择文件夹",
            "sub_dir" to "子文件夹",
            "group" to "分组",
            // BackupConfigScreen / OtherConfigScreen / AboutScreen 下沉带入 (与 app 端 values-zh/strings.xml 对齐)
            "about" to "关于",
            "app_name" to "阅读",
            "version" to "版本", // 关于页版本号标题 (AboutScreen)
            "backup_config" to "备份设置",
            "backup" to "备份",
            "backup_path" to "备份路径",
            "backup_restore" to "备份与恢复",
            "backup_summary" to "本地和 WebDav 一起备份",
            "auto_check_new_backup_s" to "打开软件时检查是否有新备份，有新备份时提示是否更新",
            "auto_check_new_backup_t" to "自动检查新备份",
            "only_latest_backup_s" to "本地备份仅保留最新备份文件",
            "only_latest_backup_t" to "仅保留最新备份",
            "restore" to "恢复",
            "restore_ignore" to "恢复忽略列表",
            "restore_ignore_summary" to "恢复时忽略一些内容不恢复，方便不同手机配置不同",
            "restore_summary" to "优先从 WebDav 恢复，长按从本地恢复",
            "select_restore_file" to "选择恢复文件",
            "set_local_password" to "设置本地密码",
            "set_local_password_summary" to "本地密码用来对备份的敏感信息加密和解密,如需在不同设备之间同步,本地密码需一致.",
            "web_dav_account" to "WebDav 账号",
            "web_dav_pw" to "WebDav 密码",
            "web_dav_set" to "WebDav 设置",
            "web_dav_set_import_old" to "WebDav 设置/导入旧版本数据",
            "web_dav_url" to "WebDav 服务器地址",
            "webdav_device_name" to "设备名称",
            "web_port_title" to "Web 端口",
            "web_service" to "Web 服务",
            "web_service_wake_lock" to "WebService唤醒锁",
            "web_service_wake_lock_summary" to "开启web服务的时候启用唤醒锁,有些手机开启唤醒锁会被杀后台",
            "user_agent" to "用户代理",
            "threads_num_title" to "更新和搜索线程数（太多会卡顿）",
            "bitmap_cache_size" to "图片绘制缓存",
            "clear_cache" to "清理缓存",
            "clear_cache_summary" to "清除已下载书籍和字体缓存",
            "clear_webview_data" to "清除 WebView 数据",
            "clear_webview_data_summary" to "清除内置浏览器所有数据",
            "shrink_database" to "压缩数据库",
            "shrink_database_summary" to "减小数据库文件的大小",
            "auto_check_update" to "自动检查更新",
            "check_update" to "检查更新",
            "update_to_variant_title" to "检查更新查找版本",
            "update_to_variant_summary" to "检查更新时查找其他签名版本",
            "pref_cronet_summary" to "使用 Cronet 网络组件",
            "server_config" to "服务器配置",
            // ServersDialog / ServerConfigDialog 下沉带入 (与 app 端 values-zh/strings.xml 对齐)
            "create" to "新建",
            "text_default" to "默认",
            "name" to "名称",
            "direct_link_upload_rule" to "直链上传规则",
            "direct_link_upload_rule_summary" to "用于导出书源书单时生成直链 URL",
            "check_source_config" to "校验设置",
            "contributors" to "开发人员",
            "contributors_summary" to "gedoor、Invinciblelee 和 Xwite 等，详情请在 GitHub 中查看",
            "join_telegram_group" to "加入 Telegram 群",
            "update_log" to "更新日志",
            "crash_log" to "崩溃日志",
            "save_log" to "保存日志",
            "create_heap_dump" to "创建堆转储",
            "record_debug_log" to "记录调试日志",
            "record_heap_dump_s" to "当应用发生OOM崩溃时保存堆转储",
            "record_heap_dump_t" to "记录堆转储",
            "record_log" to "记录日志",
            "license" to "开源许可",
            "disclaimer" to "免责声明",
            "other" to "其它",
            "other_setting" to "其它设置",
            // ThemeConfigScreen / WelcomeConfigScreen / CoverConfigScreen 下沉带入 (与 app 端 values-zh/strings.xml 对齐)
            "theme_config" to "主题设置",
            "welcome_config" to "欢迎页设置",
            "background_image" to "背景图片",
            "change_icon" to "切换图标",
            "change_icon_summary" to "切换软件显示在桌面的图标",
            "cover_config" to "封面设置",
            "cover_config_summary" to "默认封面样式",
            "cover_show_author" to "显示作者",
            "cover_show_author_summary" to "封面上显示作者",
            "cover_show_name" to "显示书名",
            "cover_show_name_summary" to "封面上显示书名",
            "customize_day_theme" to "自定义白天主题",
            "customize_night_theme" to "自定义夜间主题",
            "dark_theme" to "深色模式",
            "default_cover" to "默认封面",
            "default_home_page" to "默认主页",
            "font_scale" to "字体大小",
            "only_wifi" to "仅 WiFi",
            "only_wifi_summary" to "仅在 WiFi 下加载网络封面",
            "show_default_book_icon" to "显示默认书籍图标",
            "use_default_cover" to "总是使用默认封面",
            "use_default_cover_s" to "总是显示默认封面（不显示网络封面）",
            "bottom_nav_config" to "底栏设置",
            "bottom_nav_config_summary" to "调整底栏高度、图标大小与文本显示方式",
            "theme_list" to "主题列表",
            "theme_list_summary" to "使用、保存、导入或分享主题",
            // ThemeCustomizeDialog / ThemeListDialog 下沉带入 (与 app 端 values-zh/strings.xml 对齐)
            "accent" to "强调色",
            "background_color" to "背景色",
            "navbar_color" to "底部操作栏颜色",
            "theme_name" to "主题名称",
            "new_theme" to "新建",
            "theme_customize_title" to "编辑主题",
            "select_image" to "选择图片",
            "default_cover_count" to "已选 %1\$d 张",
            "background_image_blurring" to "背景图片虚化",
            "day_background_too_dark" to "白天背景不能太暗",
            "night_background_too_light" to "夜间背景不能太亮",
            "theme_mode" to "主题模式",
            "theme_setting" to "界面设置",
            "theme_setting_s" to "与界面/颜色相关的一些设置",
            "welcome_show_time" to "欢迎页显示时间",
            "welcome_style" to "启动界面样式",
            "welcome_style_summary" to "启动界面图片和是否显示文字等",
            "welcome_text" to "阅读|享受美好时光",
            "enable_welcome" to "启用欢迎页",
            "enable_welcome_summary" to "启动时是否显示欢迎页",
            "show_welcome_text" to "显示文字",
            "show_icon" to "显示图标",
            "day" to "白天",
            "night" to "夜间",
            "source_edit_text_max_line" to "源编辑框最大行数",
            "auto_indent" to "自动缩进",
            // ReadMenu / ReadAloudConfigScreen 下沉带入 (与 app 端 values-zh/strings.xml 对齐)
            "ps_auto_refresh" to "打开软件时自动更新书籍",
            "pt_auto_refresh" to "自动刷新",
            "click_book_open_read" to "点击视频书籍直接播放",
            "click_book_open_read_summary" to "在搜索、发现中点击视频书籍直接打开播放页，跳过详情",
            "media_button_on_exit_title" to "全程响应耳机按键",
            "media_button_on_exit_summary" to "即使退出软件也响应耳机按键",
            "read_aloud_by_media_button_title" to "耳机按键启动朗读",
            "read_aloud_by_media_button_summary" to "通过耳机按键来启动朗读",
            "auto_next_page" to "自动翻页",
            "auto_next_page_stop" to "停止自动翻页",
            // HomeScreen / MainBottomBar / MyConfigScreen / ExploreScreen 下沉带入 (与 app 端 values-zh/strings.xml 对齐)
            "bottom_line" to "我是有底线的",
            "discovery" to "发现",
            "explore_cols" to "列数",
            "explore_empty" to "当前没有发现源！",
            "explore_style" to "样式",
            "home" to "主页",
            "home_manage" to "管理组件",
            "home_tab_empty" to "此分组无组件，点击右上角+添加",
            "home_tab_manage" to "管理分组",
            "my" to "我的",
            "language" to "语言",
            "add_to_text_context_menu_s" to "长按文字在操作菜单中显示阅读",
            "add_to_text_context_menu_t" to "文字操作显示搜索",
            "show_add_to_shelf_alert_summary" to "阅读未放入书架的书籍在返回时提示放入书架",
            "show_add_to_shelf_alert_title" to "返回时提示放入书架",
            "set_book_variable" to "设置书籍变量",
            "set_source_variable" to "设置源变量",
            "sync_book_progress_s" to "进入退出阅读界面时同步阅读进度",
            "sync_book_progress_t" to "同步阅读进度",
            "sync_book_progress_plus_s" to "重新进入页面（息屏、后台返回等）或者网络变为可用时同步云端进度，同步新进度会询问",
            "sync_book_progress_plus_t" to "同步增强",
            "upload_to_remote" to "上传 WebDav",
            "sure_upload" to "远程webDav链接已存在，是否继续", // WebDav 上传覆盖确认提示 (与 app 端 values-zh/strings.xml 对齐)
            "sort_by_size" to "大小排序",
            "sort_by_time" to "时间排序",
            // 补全: SelectAction / 批量操作菜单文本 key (与 app 端 values-zh/strings.xml 对齐)
            "add_group" to "添加到分组", // 书籍/书源批量操作菜单: 添加到分组 (app 端 BookSourceActivity 用)
            "remove_group" to "从分组移除", // 书籍/书源批量操作菜单: 从分组移除 (app 端 BookSourceActivity 用)
            "add_to_group" to "加入分组", // 书籍批量操作菜单: 加入分组 (app 端 BookshelfManageActivity 用, 与 add_group 区分)
            "share_selection" to "分享所选", // 批量操作菜单: 分享所选 (旧 key, 桌面端未直接使用)
            "share_selected_source" to "分享选中源", // 书源批量操作菜单: 分享选中源 (app 端 BookSourceActivity 用)
            "check_select_source" to "校验选中书源", // 书源管理批量操作: 校验选中书源
            "export_all" to "导出全部", // 书源/书单管理: 导出全部
            "disable_update" to "禁止更新", // 书籍批量操作菜单: 禁止更新
            "export_bookshelf" to "导出书架", // 书架管理: 导出书架
            "change_source_batch" to "批量改源", // 书籍批量操作菜单: 批量改源
            "check_selected_interval" to "检查选中区间", // 书源管理批量操作: 检查选中区间
            "refresh_list" to "刷新列表", // 通用列表刷新菜单
            "checkAuthor" to "校验作者", // 书源管理批量操作: 校验作者
            "sure_clear_search_history" to "是否确认清空搜索历史？", // 搜索历史清空确认对话框
            "non_null_name_url" to "书源 URL 与名称不能为空", // 书源编辑校验提示
            "wrong_format" to "格式错误", // 通用格式校验提示
            // 桌面端 AlertDialog (替换原 javax.swing.JOptionPane) 用到的 key
            "debug_error" to "调试错误", // 调试页错误弹窗标题 (BookSourceDebugScreen.startSearch 书源未获取到)
            "no_source_found" to "未获取到书源", // 调试页错误弹窗正文
            "select_explore" to "选择发现", // 调试页发现分类选择弹窗提示
            "select_explore_kind" to "选择发现分类", // 调试页发现分类选择弹窗标题
            "no_source_code" to "暂无源码", // 调试页源码查看弹窗空源码占位
            "save_failed" to "保存失败", // 书源编辑保存校验失败标题 / catch fallback 正文
            "save_source_error" to "保存书源错误", // 书源编辑保存异常弹窗标题
            "clipboard_empty" to "剪贴板为空", // 书源编辑粘贴源剪贴板空提示
            "paste_source_error" to "粘贴书源错误", // 书源编辑粘贴源异常弹窗标题
            "enable_dangerous_api" to "启用危险 API", // 启用危险 API 确认弹窗标题
            "enable_dangerous_api_warn" to "启用危险 API 后, 书源可执行任意 JS 代码, 存在安全风险。确认启用?", // 启用危险 API 确认弹窗正文
            // 书源编辑 AppLog 文案 (desktop 专属, app 端无对应 string)
            "save_book_source_failed" to "保存书源失败",
            "debug_book_source_save_failed" to "调试书源保存失败",
            "search_book_source_save_failed" to "搜索书源保存失败",
            "book_source_copied" to "书源已复制到剪贴板",
            "copy_book_source_failed" to "复制书源失败",
            "book_source_str_copied_desktop" to "书源字符串已复制到剪贴板 (桌面端用剪贴板替代分享)",
            "share_book_source_failed" to "分享书源失败",
            "paste_book_source_failed" to "粘贴书源失败",
            // 桌面端硬编码中文替换补全 key (与 app 端 values-zh/strings.xml 对齐)
            // 通用类
            "dialog_title" to "提示",
            "not_set" to "未设置",
            "zero_disable_suffix" to "(0=禁用)",
            "settings_not_implemented" to "设置 (待实现)",
            "retry" to "重试",
            // 书源类
            "new_book_source" to "新建书源",
            "select_book_source_json" to "选择书源 JSON 文件",
            "input_book_source_url" to "请输入书源订阅 URL",
            "net_import_book_source" to "网络导入书源",
            "export_book_source_json" to "导出书源 JSON",
            "json_file_filter" to "JSON 文件 (*.json)",
            "sure_del_source" to "确认删除该书源？",
            "image_style_default" to "默认",
            "image_style_full" to "满版",
            "image_style_text" to "文字环绕",
            "image_style_single" to "单张",
            // 换源/搜索类
            "searched_count_progress" to "已搜索 %1\$d 条 / 第 %2\$d / 共 %3\$d 个源 (%4\$s)",
            "sure_del_explore_favorite" to "确认删除该发现收藏？",
            "explore_category_error" to "发现分类错误",
            "bottom_reached" to "到底了",
            "loading_error" to "加载错误",
            "loading_error_click_detail" to "加载错误 点击查看详情",
            // 替换规则类 (桌面端 ReplaceRuleScreen AlertDialog / FileDialog 标题)
            "replace_rule_net_import_title" to "网络导入替换规则",
            "replace_rule_input_url" to "请输入替换规则订阅 URL",
            "replace_rule_select_json_file" to "选择替换规则 JSON 文件",
            "replace_rule_save_json_file" to "保存替换规则 JSON 文件",
            // 发现类 (ExploreShowScreen footer 空结果占位)
            "explore_show_empty" to "空",
            // TTS/朗读类
            "previous_segment" to "上一段",
            "next_segment" to "下一段",
            "play" to "播放",
            "pause" to "暂停",
            "speech_rate" to "语速",
            "reading_not_started" to "朗读未开始",
            "reading_progress_format" to "正在朗读 %1\$d/? 章 第 %2\$d 段",
            "paused" to "已暂停",
            "stopped" to "已停止",
            "reading_completed" to "朗读完成",
            "reading_error" to "朗读出错",
            // ReadRssScreen 朗读按钮 (与 app 端 values-zh/strings.xml 对齐)
            "read_aloud" to "朗读",
            "aloud_stop" to "朗读停止",
            // 书籍编辑/导入类
            "select_cover_image" to "选择封面图片",
            "input_new_cover_url" to "请输入新的封面 URL",
            "change_cover_source" to "更换封面源",
            "select_import_book_dir" to "选择导入书籍目录",
            "filename_import_js_title" to "文件名导入 js",
            "filename_import_js_summary" to "使用js处理文件名变量src，将书名作者分别赋值到变量name author",
            "image_label_with_src" to "图片: %s",
            // Remote/WebDav 类
            "web_dav_config_not_implemented" to "WebDav 服务器配置功能暂未在桌面端实现",
            "web_dav_help_not_implemented" to "WebDav 帮助暂未在桌面端实现",
            "log_view_not_implemented" to "日志查看功能暂未在桌面端实现",
            "pending_operation" to "待操作",
            "test_connection" to "测试连接",
            "connecting" to "测试连接中...",
            "connection_success" to "连接成功",
            "connection_no_account" to "未连接: 账号或密码为空",
            "connection_failed" to "连接失败: %s",
            // WebDav 服务类型标签 (WebDavConfigScreen 测试连接成功状态文本)
            "web_dav_jianGuoYun" to "坚果云",
            "web_dav_other" to "其他 WebDav",
            "backup_success_uploaded" to "备份成功 (已上传到 WebDav)",
            "backup_failed" to "备份失败: %s",
            "local_backup_success" to "本地备份成功 (未上传到 WebDav)",
            "local_backup_failed" to "本地备份失败: %s",
            "web_dav_no_backup" to "WebDav 无备份文件",
            "restore_success" to "恢复成功 (已从云端拉取并恢复)",
            "restore_failed" to "恢复失败: %s",
            // 欢迎页类
            "seconds_unit" to "秒",
            // NumberPickerDialog 用到的 key (与 app 端 values-zh/strings.xml 对齐)
            "btn_default_s" to "默认",
            "page_touch_slop_dialog_title" to "滑动翻页阈值（0 = 系统默认值）",
            // BookSourceDebugScreen 源码查看对话框标题 (与 app 端 values-zh/strings.xml 对齐)
            "search_src" to "搜索页源码",
            "book_src" to "书籍源码",
            "toc_src" to "目录页源码",
            "content_src" to "正文页源码",
            "review_src" to "段评页源码",
            "refresh_explore" to "刷新发现",
            // 分组管理对话框 (与 app 端 values-zh/strings.xml 对齐)
            "group_name" to "分组名",
            // BookSourceEditScreen 表单 label (与 app 端 values-zh/strings.xml 对齐)
            "source_url" to "书源 URL",
            "source_name" to "书源名称",
            "source_group" to "书源分组",
            "comment" to "书源注释",
            "login_check_js" to "登录检测 JS",
            "book_url_pattern" to "详情页 URL 正则",
            "source_http_header" to "请求头",
            "concurrent_rate" to "并发率",
            "r_search_url" to "搜索 URL",
            "check_key_word" to "校验关键字",
            "r_book_list" to "列表规则",
            "r_book_name" to "书名规则",
            "r_author" to "作者规则",
            "rule_book_kind" to "分类规则",
            "rule_word_count" to "字数规则",
            "rule_last_chapter" to "最新章节规则",
            "rule_book_intro" to "简介规则",
            "rule_cover_url" to "封面规则",
            "r_book_url" to "详情页 URL 规则",
            "rule_has_more" to "下一页规则",
            "r_find_url" to "发现 URL",
            "rule_book_info_init" to "初始化规则",
            "rule_toc_url" to "目录 URL 规则",
            "rule_can_re_name" to "可重命名规则",
            "download_url_rule" to "下载 URL 规则",
            "pre_update_js" to "更新前 JS",
            "rule_chapter_name" to "章节名规则",
            "rule_chapter_url" to "章节 URL 规则",
            "rule_is_volume" to "卷规则",
            "rule_update_time" to "更新时间规则",
            "rule_is_vip" to "VIP 规则",
            "rule_is_pay" to "付费规则",
            "rule_next_toc_url" to "下一页规则",
            "rule_book_content" to "正文规则",
            "rule_should_override_url_loading" to "URL 拦截规则",
            "rule_web_js" to "WebView JS",
            "rule_source_regex" to "源码正则",
            "rule_replace_regex" to "替换规则",
            "rule_image_style" to "图片样式",
            "rule_pay_action" to "付费动作",
            // 桌面端独有 key (app 端 strings.xml 未定义)
            "cover_decode_js" to "封面解析 JS",
            "variable_comment" to "变量注释",
            "js_lib" to "JS 库",
            "sub_content_rule" to "副正文规则",
            "image_decode" to "图片解码",
            "music_cover_rule" to "音乐封面规则",
            "review_count_rule" to "段评数量规则",
            "total_review_count_rule" to "总段评数规则",
            "review_url_rule" to "段评 URL 规则",
            "review_list_rule" to "段评列表规则",
            "review_id_rule" to "段评 ID 规则",
            "avatar_rule" to "头像规则",
            "nickname_rule" to "昵称规则",
            "content_rule" to "内容规则",
            "post_time_rule" to "发布时间规则",
            "extra_rule" to "额外规则",
            "images_rule" to "图片规则",
            "vote_up_count_rule" to "点赞数规则",
            "vote_up_selected_rule" to "已点赞规则",
            "vote_down_selected_rule" to "已踩规则",
            "reply_count_rule" to "回复数规则",
            "reply_list_url" to "回复列表 URL",
            "vote_up_rule" to "点赞规则",
            "vote_down_rule" to "踩规则",
            "reply_rule" to "回复规则",
            // 书源编辑表单补充 (login_url/login_ui 已有不同值, 用独立 key 避免冲突)
            "source_login_url" to "登录 URL",
            "source_login_ui" to "登录界面",
            "delete_rule" to "删除规则",
            // 阅读配置面板 (ReadMenu 配置项 label)
            "read_config" to "阅读配置",
            "text_size" to "字号",
            "line_size" to "行距",
            "paragraph_size" to "段距",
            "background" to "背景",
            "page_turn" to "翻页",
            "page_anim_none" to "无动画",
            "page_anim_cover" to "覆盖",
            "page_anim_slide" to "滑动",
            // 搜索/文本工具栏/时间格式化 (与 app 端 values-zh/strings.xml 对齐)
            "search_result_empty" to "搜索结果为空",
            "search_result_empty_close_precision" to "%s 分组搜索结果为空，是否关闭精准搜索？",
            "search_result_empty_switch_all" to "%s 分组搜索结果为空，是否切换到全部分组？",
            "copy" to "复制",
            "cut" to "剪切",
            "paste" to "粘贴",
            "select_all" to "全选",
            "time_format_minutes" to "0 分钟",
            "time_format_hours_minutes" to "%1\$d 小时 %2\$d 分钟",
            "time_format_hours" to "%d 小时",
            "time_format_minutes_only" to "%d 分钟",
            "time_format_seconds" to "%d 秒",
            // 书源编辑/调试菜单项 (与 app 端 values-zh/strings.xml 对齐)
            "book_source_tutorial" to "书源教程",
            "js_tutorial" to "JS 教程",
            "regex_tutorial" to "正则教程",
            "debug_search_hint" to "调试搜索>>输入关键字，如：",
            "debug_explore_hint" to "调试发现>>输入发现URL，如：",
            "debug_book_info_hint" to "调试详情页>>输入详情页URL，如：",
            "debug_toc_hint" to "调试目录页>>输入目录页URL，如：",
            "debug_content_hint" to "调试正文页>>输入正文页URL，如：",
            "system" to "系统",
            // ===== P0 Dialog 下沉新增 i18n key (16 个 Dialog 用) =====
            // TextDialog
            "text_too_large" to "数据太大，无法全部显示…",
            // AppLogDialog
            "log_level_all" to "全部",
            "log_level_error" to "错误",
            "log_level_warn" to "警告",
            "log_level_info" to "信息",
            "log_level_debug" to "调试",
            "log_stack_trace" to "堆栈信息",
            // BookmarkDialog
            "bookmark_content" to "内容",
            "bookmark_note" to "备注内容",
            // SearchScopeDialog
            "search_scope" to "搜索范围",
            // VariableDialog
            "source_variable_tab" to "源变量",
            "book_variable_tab" to "书籍变量",
            "variable_key" to "变量名",
            "variable_value" to "变量值",
            "variable_edit_title" to "编辑变量",
            "variable_empty" to "暂无变量",
            // GroupEditDialog
            "group_edit" to "编辑分组",
            "group_add" to "添加分组",
            "allow_drop_down_refresh" to "允许下拉刷新",
            "book_sort_default" to "默认",
            "book_sort_reading_time" to "按阅读时间",
            "book_sort_update_time" to "按更新时间",
            "book_sort_name" to "按书名",
            "book_sort_manual" to "手动排序",
            "book_sort_comprehensive" to "综合排序",
            "book_sort_author" to "按作者",
            // TxtTocRuleEditDialog
            "txt_toc_rule_edit_name" to "名称",
            "txt_toc_rule_edit_rule" to "规则",
            "txt_toc_rule_edit_example" to "示例",
            "txt_toc_rule_edit_name_required" to "名称不能为空",
            "txt_toc_rule_edit_regex_error" to "正则语法错误或不支持(txt)",
            "txt_toc_rule_edit_copy_success" to "已复制",
            // DictRuleEditDialog
            "dict_rule_edit_name" to "名称",
            "dict_rule_edit_url_rule" to "URL 规则",
            "dict_rule_edit_show_rule" to "显示规则",
            "dict_rule_edit_copy_success" to "已复制",
            // SourceFilterEditDialog
            "source_filter_rule_edit_name" to "规则名",
            "source_filter_rule_edit_pattern" to "规则",
            "source_filter_rule_edit_invalid_pattern" to "正则无效或为空",
            "source_filter_rule_edit_title_add" to "添加屏蔽规则",
            "source_filter_rule_edit_title_edit" to "屏蔽规则",
            // ContentEditDialog
            "content_edit_reset" to "重置",
            "content_edit_copy_all" to "复制全部",
            "content_edit_copy_success" to "已复制",
            // ClickActionDialog
            "click_regional_config" to "点击区域设置",
            "select_action" to "选择动作",
            "menu" to "菜单",
            "next_page" to "下一页",
            "prev_page" to "上一页",
            "read_aloud_prev_paragraph" to "朗读上一段",
            "read_aloud_next_paragraph" to "朗读下一段",
            "bookmark_add" to "添加书签",
            "replace_state_change" to "替换状态切换",
            "read_aloud_pause_resume" to "朗读暂停/继续",
            // PageKeyDialog
            "prev_page_key" to "上一页按键",
            "next_page_key" to "下一页按键",
            "reset" to "重置",
            // SpeakEngineDialog
            "system_default" to "系统默认",
            // ReadAloudDialog
            "prev_sentence" to "上一句",
            "next_sentence" to "下一句",
            "audio_play" to "播放",
            "set_timer" to "设定时间",
            "timer_m" to "%d 分钟",
            "read_aloud_speed" to "语速",
            "flow_sys" to "跟随系统",
            "tts_speech_reduce" to "语速减",
            "tts_speech_add" to "语速加",
            "main_menu" to "主菜单",
            "to_backstage" to "转到后台",
            // SourcePickerDialog
            "select_book_source" to "选择书源",
            "change_source_delay" to "换源延迟",
            // P0: TTS onError 错误回调 (DesktopHttpTtsPlayer, 非 @Composable 上下文用 jvmGetString)
            "tts_error_prepare_no_url" to "prepare 失败: 未设置 URL",
            "tts_error_prepare_exception" to "prepare 异常: %s",
            "tts_error_resume_failed" to "恢复播放失败: %s",
            "tts_error_play_exception" to "播放异常: %s",
            "tts_error_http_connect_failed" to "HTTP 连接失败: %s",
            "tts_error_input_stream_null" to "InputStream 为 null",
            "tts_error_unsupported_audio_format" to "不支持的音频格式 (桌面端仅支持 WAV/PCM/AU/AIFF; MP3 需引入 MP3 SPI): %s",
            "tts_error_read_stream_failed" to "读取音频流失败: %s",
            "tts_error_audio_line_unavailable" to "音频输出线不可用: %s",
            "tts_error_open_line_failed" to "打开音频输出线失败: %s",
            "tts_error_source_line_not_ready" to "播放失败: SourceDataLine 未就绪",
            "tts_error_audio_stream_not_ready" to "播放失败: AudioInputStream 未就绪",
            "tts_error_start_failed" to "启动播放失败: %s",
            "tts_error_read_stream_interrupted" to "读取音频流中断: %s",
            "tts_error_write_line_failed" to "写入音频线失败: %s",
            // P1: 调试日志 (BookSourceDebugScreen logs.add, 非 @Composable 上下文用 jvmGetString)
            "debug_explore_error" to "获取发现出错\n%s",
            "debug_explore_json_error" to "获取发现出错 JSON 数据错误\n%s",
            "debug_source_not_found" to "ERROR:未找到书源 %s",
            // HttpTts 导入 (ReadAloudConfigScreen 接入 DesktopImportDialog, 与 ReplaceRuleScreen
            // 的 replace_rule_net_import_title/replace_rule_input_url/replace_rule_select_json_file
            // 命名风格对齐; import_tts 与 app 端 values/strings.xml line 701 一致)
            "import_tts" to "导入 TTS",
            "http_tts_net_import_title" to "网络导入 TTS",
            "http_tts_input_url" to "请输入 TTS 订阅 URL",
            "http_tts_select_json_file" to "选择 TTS JSON 文件",
            // 桌面端硬编码中文 i18n 补全 key
            "back" to "返回",
            "change_source" to "换源",
            "cover" to "封面",
            "no_lyrics" to "暂无歌词",
            "speed" to "倍速",
            "play_mode" to "播放模式",
            "log_saved" to "日志已保存",
            "save_log_failed" to "保存日志失败",
            "heap_dump_saved" to "堆转储已保存",
            "save_heap_dump_failed" to "保存堆转储失败",
            "found_new_version" to "发现新版本",
            "download_now" to "前往下载",
            "net_import_theme" to "网络导入主题",
            "input_theme_url" to "请输入主题订阅 URL",
            "import_theme_success" to "导入成功, 共 %d 个主题",
            "clipboard_empty_or_invalid" to "剪贴板为空或格式不对",
            "format_invalid_add_failed" to "格式不对,添加失败",
            "copied_to_clipboard" to "已复制到剪贴板",
            "copy_failed" to "复制失败",
            "load_chapter_content_failed" to "加载章节内容失败",
            "text_action" to "文字操作",
            "loading_chapter_content" to "正在加载章节内容...",
            "address_copied" to "已复制地址",
            "copy_address" to "复制地址",
            "open_failed" to "打开失败: %s",
            "open_in_browser" to "浏览器打开",
            "restore_from_local_prompt" to "将从本地备份恢复。",
            "clear_cache_success" to "清缓存成功",
            "export_bookmark_json" to "导出书签 JSON",
            "export_success" to "导出成功",
            "export_bookmark_md" to "导出书签 Markdown",
            "no_book" to "没有书籍",
            "resolution" to "分辨率",
            "reload" to "重新加载",
            // ReviewListDialog 下沉带入 (与 app 端 values-zh/strings.xml 对齐)
            "review_post_hint" to "想说点什么？",
            "reply_review" to "回复",
            "review_replies_detail_title" to "评论详情",
            "review_replies_section_title" to "全部回复 · %1\$d",
            "review_list_section_title" to "全部评论 · %1\$s",
            "review_sort_hot" to "最热",
            "review_sort_latest" to "最新",
            "review_expand" to "展开",
            "review_collapse" to "收起",
            "confirm_delete_review" to "确定删除这条评论？",
            "vote_up" to "点赞",
            "vote_down" to "点踩",
            "review_replies_count" to "全部 %1\$d 条回复 >",
            // desktop 模块中文字面量国际化新增 key (desktop 专属文案 + 复用 app 端语义的 key)
            "check_source_cancelled" to "已取消书源校验",
            "check_source_in_progress" to "已有书源在校验,等完成后再试",
            "check_source_progress_msg" to "校验书源 %1\$d/%2\$d %3\$s",
            "check_source_completed" to "书源校验完成",
            "check_source_error" to "书源校验出错\n%s",
            "new_book_source_added" to "新建书源已添加: %s",
            "no_source_selected" to "未选中任何书源",
            "export_source_no_selection" to "导出书源: 未选中任何书源",
            "export_source_db_empty" to "导出书源: 数据库查询为空",
            "export_source_cancelled" to "导出书源: 用户取消选择",
            "export_source_done" to "导出书源完成, 共 %1\$d 条 → %2\$s",
            "export_source_write_failed" to "导出书源: 写文件失败",
            "share_source_no_selection" to "分享书源: 未选中任何书源",
            "share_source_db_empty" to "分享书源: 数据库查询为空",
            "share_source_copied" to "分享书源已复制到剪贴板, 共 %1\$d 条",
            "import_source_cancelled" to "导入书源: 用户取消选择",
            "debug_fx_default" to "系统::http://xxx",
            "import_state_new" to "新增",
            "import_state_update" to "更新",
            "import_state_existing" to "已有",
            // ImportItemsDialog 标题/菜单 (与 app 端 values-zh/strings.xml 对齐)
            "import_book_source" to "导入书源",
            "import_replace_rule" to "导入替换规则",
            "import_dict_rule" to "导入字典规则",
            "import_txt_toc_rule" to "导入 TXT 目录规则",
            "import_source_filter_rule" to "导入屏蔽规则",
            "import_theme" to "导入主题",
            "import_http_tts" to "导入 TTS", // RuleSubScreen 语音源订阅标题 (与 import_tts 同文案)
            "select_new_source" to "选中新增源",
            "select_update_source" to "选中更新源",
            // legado:// deep link 未支持类型提示 (ADD_TO_BOOKSHELF/READ_CONFIG/UNKNOWN, 各端共用)
            "deep_link_type_not_supported" to "该 legado:// 导入类型暂未支持: %s",
            "rule_sub_load_failed" to "规则订阅界面获取数据失败\n%s",
            "input_valid_url" to "请输入有效的 URL",
            "check_update_failed" to "检查更新失败\n%s",
            "check_update_failed_no_msg" to "检查更新失败",
            "already_latest_version" to "已是最新版本",
            "desktop_smoke_test_js_hint" to "提示: 若错误为 UnsatisfiedLinkError, 请先执行:",
            "desktop_smoke_test_db_count" to "bookSourceDao.allCount() = %s (空表期望 0)",
            "desktop_install_mode_not_portable" to "[legado-desktop] install mode = %s (portable.root not set, 下游走 portable.txt 标记/系统数据目录)",
            "image_decode_failed_bytes" to "image.decode: 无法解码图片字节(%s bytes)",
            "image_encode_unsupported_format" to "image.encode: 不支持的格式 %s，仅 png/jpg/webp",
            "image_encode_write_failed" to "image.encode: ImageIO.write 失败 format=%s",
            "image_split_rows_cols_positive" to "image.split: rows/cols 必须为正数(%1\$s,%2\$s)",
            "image_split_exceeds_size" to "image.split: 切块数超过像素尺寸(%1\$sx%2\$s / %3\$s行%4\$s列)",
            "image_stitch_imgs_empty" to "image.stitch: imgs 为空",
            "image_stitch_direction_invalid" to "image.stitch: direction 仅支持 h/v，收到 %s",
            "image_ref_type_invalid" to "image: 参数不是 image.decode/split/stitch/crop 返回的 ImageRef(%s)",
            "desktop_audio_play_error" to "桌面音频播放出错\n%s",
            "desktop_audio_no_resource_url" to "未获取到资源链接",
            "desktop_audio_load_failed" to "桌面音频加载失败\n%s",
            "desktop_lrc_load_failed" to "桌面歌词加载失败\n%s",
            "desktop_audio_save_read_failed" to "桌面 saveRead 失败\n%s",
            "desktop_audio_save_failed" to "桌面 save 失败\n%s",
            "desktop_audio_get_book_source_failed" to "桌面 getBookSource 失败\n%s",
            "desktop_cookie_set_error" to "桌面端设置 cookie 出错 domain=%s cookie=%s",
            "download_jslib_failed" to "下载jsLib-%s失败",
            "rhino_deprecated_unreachable" to "rhino 已弃用,JsEngines.type 固定 QUICKJS,不应到达 type=%s",
            "upload_url_not_configured" to "上传url未配置",
            "download_url_rule_not_configured" to "下载地址规则未配置",
            "upload_failed_with_body" to "上传失败,%s",
            "desktop_backstage_webview_unsupported" to "桌面端不支持 BackstageWebView (依赖 android.webkit.WebView), 请改用 HTTP 路径或选用不依赖 webView 的书源",
            "book_info_copied" to "已复制书籍信息",
            "need_more_time_load_content" to "正文过长时可能需要更多时间加载内容",
            "clear_cache_failed" to "清缓存失败: %s\n%s",
            "intro_action_dispatch_failed" to "简介动作派发失败: %s",
            "no_book_source" to "无书源",
            "select_cover_cancelled" to "选择封面: 用户取消选择",
            "bookshelf_manage_load_groups_failed" to "书架管理界面获取分组数据失败\n%s",
            "bookshelf_manage_load_sources_failed" to "书架管理界面获取书源数据失败\n%s",
            "bookshelf_manage_load_books_failed" to "书架管理界面获取书籍列表失败\n%s",
            "export_bookshelf_json" to "导出书架 JSON",
            "export_bookshelf_cancelled" to "导出书架: 用户取消选择",
            "delete_local_book_file_failed" to "删除本地书源文件失败: %s\n%s",
            "add_book_url_failed" to "添加 %s 失败\n%s",
            "add_book_url_success" to "%1\$d/%2\$d 成功",
            "add_book_url_all_failed" to "添加网址失败",
            "adding_book" to "添加中...",
            "read_file_failed" to "读取文件失败",
            "import_book_failed" to "导入<%s>失败\n%s",
            "import_complete" to "导入完成 %d",
            "import_bookshelf_failed" to "导入书架失败\n%s",
            "importing_book" to "导入中...",
            "url_import" to "URL 导入",
            "upload_url_empty" to "上传Url不能为空",
            "download_url_rule_empty" to "下载Url规则不能为空",
            "summary_empty" to "注释不能为空",
            "copy_rule_failed" to "复制规则失败",
            "clear_all_cache_failed" to "清缓存失败\n%s",
            "shrink_database_failed" to "收缩数据库失败\n%s",
            "more" to "更多",
            "source_invalid" to "书源失效",
            "widget_count" to "%d个组件",
            "no_widget" to "暂无组件",
            "home_style_rank_list" to "排行榜",
            "home_style_four_row" to "四行",
            "home_style_infinite_grid" to "无限网格",
            "home_style_cover_row" to "封面行",
            "load_default_http_tts_failed" to "加载默认 HttpTTS 失败\n%s",
            "webdav_sync_progress_failed" to "WebDav 同步阅读进度失败\n%s",
            "force_refresh_busy" to "正在刷新中, 请稍后再试",
            "force_refresh_start" to "开始强制刷新 %d 本",
            "refresh_complete" to "刷新完成",
            "copy_chapter_title" to "复制章节标题",
            "lookup_word" to "查词",
            "browser_search" to "浏览器搜索",
            "translate" to "翻译",
            "select_and_copy_first_hint" to "请先选中并复制文字",
            "replace_rule_copied_to_clipboard" to "替换规则已复制到剪贴板",
            "dict_rule_load_failed" to "字典规则界面获取数据失败\n%s",
            "import_default_dict_rule_failed" to "导入默认字典规则失败",
            "import_dict_rule_user_canceled" to "导入字典规则: 用户取消选择",
            "export_dict_rule_no_selection" to "导出字典规则: 未选中任何规则",
            "export_dict_rule_user_canceled" to "导出字典规则: 用户取消选择",
            "export_dict_rule_done" to "导出字典规则完成, 共 %1\$d 条 → %2\$s",
            "export_dict_rule_failed" to "导出字典规则失败",
            "explore_update_groups_error" to "发现界面更新分组出错",
            "explore_update_data_error" to "发现界面更新数据出错",
            "explore_pinned_source_not_found" to "发现收藏: 书源未找到 %s",
            "explore_js_error" to "JS错误%s",
            "import_replace_rule_user_canceled" to "导入替换规则: 用户取消选择",
            "export_replace_rule_no_selection" to "导出替换规则: 未选中任何规则",
            "rss_articles_empty" to "暂无文章",
            "rss_no_content_rule_hint" to "无正文规则或内容为空\n请用浏览器打开",
            "rss_sources_empty_hint" to "暂无 RSS 源\n请在书架中添加 type 含 rss 位的书籍",
            "latest_version" to "最新版本: %s",
            "search_content_failed" to "书内搜索失败\n%s",
            "restore_from_local_failed" to "本地恢复失败\n%s",
            "get_webdav_backup_list_failed" to "获取WebDav备份列表出错\n%s",
            "webdav_backup_failed" to "WebDav 备份失败\n%s",
            "webdav_local_backup_failed" to "WebDav 本地备份失败\n%s",
            "webdav_restore_failed" to "WebDav 恢复失败\n%s",
            "all_bookmark_load_data_failed_log" to "所有书签界面获取数据失败\n%s",
            "export_bookmark_no_book" to "导出书签: 没有书籍",
            "export_bookmark_user_cancelled" to "导出书签: 用户取消选择",
            "export_failed_log" to "导出失败\n%s",
            "export_failed" to "导出失败\n%s",
            "save_success" to "保存成功",
            "delete_success" to "删除成功",
            "delete_http_tts_failed" to "删除 HttpTTS 失败",
            "copy_http_tts_failed" to "复制 HttpTTS 失败",
            "desktop_test_not_implemented" to "桌面端测试功能待实现",
            "load_font_failed" to "加载字体失败: %s",
            "load_http_tts_list_failed" to "加载 HttpTTS 列表失败",
            "import_http_tts_user_cancelled" to "导入 HttpTTS: 用户取消选择",
            "change_chapter_source_load_toc_error_log" to "单章换源获取目录出错\n%s",
            "change_source_load_toc_error_log" to "换源获取目录出错\n%s",
            "audio_cover_load_failed_log" to "桌面音频封面加载失败: %s\n%s",
            "cbz_import_parse_failed_log" to "Cbz 导入解析失败: %s\n%s",
            "epub_import_parse_failed_log" to "Epub 导入解析失败: %s\n%s",
            "filename_import_js_input_log" to "文件名导入 js 已输入 (桌面端暂不持久化): %s",
            "import_local_book_user_cancelled" to "导入本地书籍: 用户取消选择目录",
            "remote_book_webdav_not_sunk_log" to "远程书籍: WebDav 客户端未下沉, 桌面端暂不加载远程列表",
            "review_no_current_book" to "无当前书籍",
            "review_no_source" to "无书源",
            "review_load_failed" to "评论加载失败: %s",
            "review_operation_failed" to "操作失败: %s",
            "review_no_action_rule" to "书源未配置此操作规则",
            "current_chapter_prefix" to " / 当前章节:",
            "import_default_txt_toc_rule_failed" to "导入默认 TXT 目录规则失败",
            "import_txt_toc_rule_user_cancelled" to "导入 TXT 目录规则: 用户取消选择",
            "export_txt_toc_rule_no_selection" to "导出 TXT 目录规则: 未选中任何规则",
            "export_txt_toc_rule_user_cancelled" to "导出 TXT 目录规则: 用户取消选择",
            "export_txt_toc_rule_done_log" to "导出 TXT 目录规则完成, 共 %s 条 → %s",
            "export_txt_toc_rule_failed" to "导出 TXT 目录规则失败",
            "source_filter_rule_load_data_failed_log" to "书源过滤规则界面获取数据失败\n%s",
            "import_source_filter_rule_user_cancelled" to "导入书源过滤规则: 用户取消选择",
            "export_source_filter_rule_no_selection" to "导出书源过滤规则: 未选中任何规则",
            "export_source_filter_rule_user_cancelled" to "导出书源过滤规则: 用户取消选择",
            "export_source_filter_rule_done_log" to "导出书源过滤规则完成, 共 %s 条 → %s",
            "export_source_filter_rule_failed" to "导出书源过滤规则失败",
            // 桌面视频 all-in mpv (VideoPlayerScreen / MpvPlayer / MpvDetector)
            "mpv_not_found" to "未检测到 mpv 播放器",
            "mpv_install_guide" to "视频播放依赖 mpv (https://mpv.io)\nWindows: winget install mpv 或 scoop install mpv,\n也可官网下载后把 mpv.exe 所在目录加入 PATH,\n或在配置项 mpvPath 中指定完整路径",
            "mpv_open_website" to "打开 mpv 官网",
            "mpv_auto_download" to "自动下载便携版",
            "mpv_downloading" to "正在准备 mpv 便携版...",
            "mpv_downloading_percent" to "正在下载 mpv 便携版... %s%%",
            "mpv_download_failed" to "下载 mpv 失败: %s\n可改用 winget/scoop 安装, 或手动下载后在配置项 mpvPath 指定",
            "mpv_redetect" to "重新检测",
            "mpv_open_in_browser" to "浏览器直接打开",
            "mpv_open_in_browser_warn" to "已用系统默认程序打开视频流 (无防盗链请求头, 部分源可能无法播放)",
            "mpv_detached_playing" to "已在独立 mpv 窗口中播放 (当前系统不支持窗口嵌入)",
            "video_mpv_launch_error_log" to "桌面视频启动 mpv 出错\n%s",
            "video_mpv_ipc_error_log" to "mpv IPC 桥连接失败, 进度回写/自动连播/快捷键不可用: %s",
            "video_play_error_mpv" to "桌面视频播放出错 (mpv: %s)",
            "manga_cbz_load_chapter_list_error_log" to "桌面漫画(cbz)获取章节列表出错\n%s",
            "manga_load_chapter_list_error_log" to "桌面漫画获取章节列表出错\n%s",
            "manga_load_chapter_list_failed" to "获取章节列表失败: %s",
            "source_not_exists" to "书源不存在",
            "chapter_list_not_loaded" to "章节列表未加载",
            "chapter_not_exists" to "章节不存在: %s",
            "manga_cbz_load_chapter_content_error_log" to "桌面漫画(cbz)获取章节内容出错\n%s",
            "manga_load_chapter_content_error_log" to "桌面漫画获取章节内容出错\n%s",
            "load_failed" to "加载失败: %s",
            "content_empty" to "正文内容为空",
            "content_no_images" to "正文没有图片",
            "manga_load_chapter_error_log" to "桌面漫画加载章节出错\n%s",
            "load_error" to "加载出错: %s",
            "manga_pre_download_chapter_failed_log" to "桌面漫画预下载章节 %s 失败\n%s",
            "manga_save_read_progress_error_log" to "桌面漫画保存阅读进度出错\n%s",
            "manga_image_load_failed_log" to "桌面漫画图片加载失败: %s\n%s",
            "toc_load_chapter_failed_log" to "目录界面加载章节失败\n%s",
            "toc_load_bookmark_failed_log" to "目录界面获取书签数据失败\n%s",
            "toc_reload_bookmark_failed_log" to "目录界面重载书签失败\n%s",
            "txt_toc_rule_load_data_failed_log" to "TXT 目录规则界面获取数据失败\n%s",
            "theme_arcoblue_light" to "Arcoblue 浅",
            "theme_arcoblue_dark" to "Arcoblue 深",
            "theme_arcogreen_light" to "Arcogreen 浅",
            "theme_arcogreen_dark" to "Arcogreen 深",
            "theme_arcoorange_light" to "Arcoorange 浅",
            "theme_arcoorange_dark" to "Arcoorange 深",
            "theme_arcopurple_light" to "Arcopurple 浅",
            "theme_arcopurple_dark" to "Arcopurple 深",
            "theme_arcored_light" to "Arcored 浅",
            "theme_arcored_dark" to "Arcored 深",
            // iOS 端功能待接入 / 不支持提示 (统一硬编码文案, 便于后续逐个实现时删除)
            "ios_check_update_not_implemented" to "iOS 端检查更新功能待接入",
            "ios_crash_log_not_implemented" to "iOS 端崩溃日志功能待接入",
            "ios_save_log_not_implemented" to "iOS 端保存日志功能待接入",
            "ios_heap_dump_not_supported" to "iOS 端不支持堆转储",
            "ios_prev_chapter_not_implemented" to "iOS 端上一章待接入",
            "ios_next_chapter_not_implemented" to "iOS 端下一章待接入",
            "ios_video_playback_not_implemented" to "iOS 端视频播放待接入",
            "ios_progress_drag_not_implemented" to "iOS 端进度拖动待接入",
            "ios_playback_speed_not_implemented" to "iOS 端倍速待接入",
            "ios_retry_not_implemented" to "iOS 端重试待接入",
            "ios_welcome_duration_not_implemented" to "iOS 端启动时长待接入",
            "ios_welcome_bg_image_not_implemented" to "iOS 端启动背景图选取待接入",
            "ios_bookshelf_layout_not_implemented" to "iOS 端书架布局待接入",
            "ios_search_layout_not_implemented" to "iOS 端搜索布局待接入",
            "ios_bottom_bar_config_not_implemented" to "iOS 端底栏配置待接入",
            "ios_theme_list_not_implemented" to "iOS 端主题列表待接入",
            "ios_custom_light_theme_not_implemented" to "iOS 端自定义日间主题待接入",
            "ios_custom_dark_theme_not_implemented" to "iOS 端自定义夜间主题待接入",
            "ios_font_scale_not_implemented" to "iOS 端字体缩放待接入",
            "ios_source_edit_max_line_not_implemented" to "iOS 端源编辑行数待接入",
            "ios_local_password_not_implemented" to "iOS 端本地密码待接入",
            "ios_user_agent_not_implemented" to "iOS 端 UserAgent 设置待接入",
            "ios_book_tree_uri_not_implemented" to "iOS 端书籍存储路径待接入",
            "ios_check_source_not_implemented" to "iOS 端校验源配置待接入",
            "ios_upload_rule_not_implemented" to "iOS 端上传规则待接入",
            "ios_bitmap_cache_not_implemented" to "iOS 端位图缓存设置待接入",
            "ios_pre_download_num_not_implemented" to "iOS 端预下载数量待接入",
            "ios_web_port_not_implemented" to "iOS 端 Web 端口待接入",
            "ios_clean_cache_not_implemented" to "iOS 端清理缓存待接入",
            "ios_clear_webview_data_not_supported" to "iOS 端不支持清理 WebView 数据",
            "ios_shrink_database_not_implemented" to "iOS 端压缩数据库待接入",
            "ios_thread_count_not_implemented" to "iOS 端线程数设置待接入",
            "ios_custom_page_key_not_implemented" to "iOS 端自定义翻页按键待接入",
            "ios_default_cover_not_implemented" to "iOS 端默认封面选择待接入",
            "ios_cover_height_not_implemented" to "iOS 端封面高度设置待接入",
            "ios_tts_engine_not_implemented" to "iOS 端 TTS 引擎待接入",
            "ios_sys_tts_config_not_implemented" to "iOS 端系统 TTS 配置待接入",
            "ios_backup_path_not_implemented" to "iOS 端备份路径选择待接入",
            "ios_webdav_backup_not_implemented" to "iOS 端 WebDav 备份待接入",
            "ios_webdav_restore_not_implemented" to "iOS 端 WebDav 恢复待接入",
            "ios_restore_ignore_not_implemented" to "iOS 端忽略恢复待接入",
            "ios_theme_mode_change_not_implemented" to "iOS 端主题模式切换待接入",
            "ios_web_service_not_implemented" to "iOS 端 Web 服务待接入",
            "ios_add_replace_rule_not_implemented" to "iOS 端新增替换规则待接入",
            "ios_edit_replace_rule_not_implemented" to "iOS 端编辑替换规则待接入",
            "ios_manage_replace_rules_not_implemented" to "iOS 端管理替换规则待接入",
            "ios_add_rule_sub_not_implemented" to "新增订阅功能待接入",
            "ios_edit_rule_sub_not_implemented" to "编辑订阅功能待接入",
            "ios_open_rule_sub_not_implemented" to "打开订阅功能待接入",
            "ios_edit_book_source_not_implemented" to "编辑书源功能暂未接入",
            "ios_import_default_txt_toc_rule_not_supported" to "iOS 端暂不支持导入默认 TXT 目录规则",
            "ios_import_default_dict_rule_not_supported" to "iOS 端暂不支持导入默认字典规则",
            "cannot_access_selected_dir" to "无法访问所选目录",
            "ios_webdav_client_not_available_log" to "iOS 端 WebDav 客户端未下沉, 远程书籍列表加载暂不可用",
            // iOS 端音频播放待接入提示 (与视频/漫画的同类 key 分开, 便于逐个实现时删除)
            "ios_cover_switch_not_implemented" to "iOS 端封面切换待接入",
            "ios_audio_playback_not_implemented" to "iOS 端音频播放待接入",
            "ios_prev_track_not_implemented" to "iOS 端上一曲待接入",
            "ios_next_track_not_implemented" to "iOS 端下一曲待接入",
            "ios_play_mode_switch_not_implemented" to "iOS 端播放模式切换待接入",
            "ios_audio_progress_drag_not_implemented" to "iOS 端进度拖动待接入",
            "ios_audio_timer_not_implemented" to "iOS 端定时待接入",
            "ios_audio_playback_speed_not_implemented" to "iOS 端倍速待接入",
            // 鸿蒙端功能待接入 / 不支持提示 (统一硬编码文案, 便于后续逐个实现时删除; 与 iOS 端 key 对称)
            // ThemeConfig
            "ohos_bookshelf_layout_not_implemented" to "鸿蒙端书架布局待接入",
            "ohos_search_layout_not_implemented" to "鸿蒙端搜索布局待接入",
            "ohos_bottom_bar_config_not_implemented" to "鸿蒙端底栏配置待接入",
            "ohos_theme_list_not_implemented" to "鸿蒙端主题列表待接入",
            "ohos_custom_light_theme_not_implemented" to "鸿蒙端自定义日间主题待接入",
            "ohos_custom_dark_theme_not_implemented" to "鸿蒙端自定义夜间主题待接入",
            "ohos_font_scale_not_implemented" to "鸿蒙端字体缩放待接入",
            "ohos_source_edit_max_line_not_implemented" to "鸿蒙端源编辑行数待接入",
            // ReadConfig (朗读设置)
            "ohos_tts_engine_not_implemented" to "鸿蒙端 TTS 引擎待接入",
            "ohos_sys_tts_config_not_implemented" to "鸿蒙端系统 TTS 配置待接入",
            // OtherConfig
            "ohos_local_password_not_implemented" to "鸿蒙端本地密码待接入",
            "ohos_user_agent_not_implemented" to "鸿蒙端 UserAgent 设置待接入",
            "ohos_book_tree_uri_not_implemented" to "鸿蒙端书籍存储路径待接入",
            "ohos_check_source_not_implemented" to "鸿蒙端校验源配置待接入",
            "ohos_upload_rule_not_implemented" to "鸿蒙端上传规则待接入",
            "ohos_bitmap_cache_not_implemented" to "鸿蒙端位图缓存设置待接入",
            "ohos_pre_download_num_not_implemented" to "鸿蒙端预下载数量待接入",
            "ohos_web_port_not_implemented" to "鸿蒙端 Web 端口待接入",
            "ohos_clean_cache_not_implemented" to "鸿蒙端清理缓存待接入",
            "ohos_clear_webview_data_not_supported" to "鸿蒙端不支持清理 WebView 数据",
            "ohos_shrink_database_not_implemented" to "鸿蒙端压缩数据库待接入",
            "ohos_thread_count_not_implemented" to "鸿蒙端线程数设置待接入",
            "ohos_custom_page_key_not_implemented" to "鸿蒙端自定义翻页按键待接入",
            // BackupConfig
            "ohos_backup_path_not_implemented" to "鸿蒙端备份路径选择待接入",
            "ohos_webdav_backup_not_implemented" to "鸿蒙端 WebDav 备份待接入",
            "ohos_webdav_restore_not_implemented" to "鸿蒙端 WebDav 恢复待接入",
            "ohos_restore_ignore_not_implemented" to "鸿蒙端忽略恢复待接入",
            // CoverConfig
            "ohos_default_cover_not_implemented" to "鸿蒙端默认封面选择待接入",
            "ohos_cover_height_not_implemented" to "鸿蒙端封面高度设置待接入",
            // WelcomeConfig
            "ohos_welcome_duration_not_implemented" to "鸿蒙端启动时长待接入",
            "ohos_welcome_bg_image_not_implemented" to "鸿蒙端启动背景图选取待接入",
            // iOS 端 Toast / AppLog 硬编码文案补 key 第二批 (业务文案, 各端可复用)
            "format_invalid" to "格式不对",
            "copied_rules_to_clipboard_count" to "已复制 %d 条规则到剪贴板",
            "copied_rule_to_clipboard" to "已复制规则到剪贴板",
            "copied_bookmarks_to_clipboard_count" to "已复制 %d 条书签到剪贴板",
            "copied_markdown_to_clipboard" to "已复制 Markdown 到剪贴板",
            "import_complete_with_fail_count" to "导入完成 成功 %1\$d 失败 %2\$d",
            "upload_success" to "上传成功",
            "upload_failed" to "上传失败",
            "download_success" to "下载成功",
            "book_source_disabled" to "已禁用书源",
            "import_local_book_failed_log" to "导入本地书籍失败\n%s",
            "get_toc_failed_log" to "获取目录失败\n%s",
            "download_remote_book_failed_log" to "下载远程书籍<%s>失败",
            "intro_action_failed_log" to "简介动作执行失败\n%s",
            "pick_image_failed_log" to "选图失败: 无法获取路径",
            // iOS 端 Toast / AppLog 硬编码文案补 key 第二批 (业务文案, 各端可复用)
            "new_book_source_added_log" to "新建书源已添加: %s",
            "save_book_source_failed_log" to "保存书源失败",
            "debug_source_save_failed_log" to "调试书源保存失败",
            "search_in_book_failed_log" to "书内搜索失败\n%s",
            "bookmark_load_failed_log" to "所有书签界面获取数据失败\n%s",
            "change_source_toc_failed_log" to "换源获取目录出错\n%s",
            "change_chapter_source_toc_failed_log" to "单章换源获取目录出错\n%s",
            "load_toc_failed" to "加载目录失败",
            "bookshelf_manage_load_group_failed_log" to "书架管理加载分组失败\n%s",
            "bookshelf_manage_load_book_failed_log" to "书架管理加载书籍失败\n%s",
            "ios_unlock_scope_failed_access_selected_dir_log" to "iOS 端解锁安全作用域失败, 无法访问所选目录",
            "ios_unlock_scope_failed_access_subdir_log" to "iOS 端解锁安全作用域失败, 无法访问子目录",
            "ios_unlock_scope_failed_access_parent_dir_log" to "iOS 端解锁安全作用域失败, 无法访问上级目录",
            "ios_unlock_scope_failed_scan_dir_log" to "iOS 端解锁安全作用域失败, 无法扫描目录",
            "ios_user_cancel_select_import_dir_log" to "iOS 端用户取消选择导入目录",
            "ios_filename_import_js_input_log" to "文件名导入 js 输入: %s",
            // iOS 独有 key (桌面端/app 端 strings.xml 无对应 string)
            "read_style" to "阅读样式",
            "video_play" to "视频播放",
            "manga_read" to "漫画阅读",
            // 鸿蒙端 ASSOCIATION / JS_EDIT 路由 Screen 用到的 key
            "association_import" to "关联导入",
            "js_edit" to "JS 编辑",
            "run" to "运行",
            "result" to "结果",
            "ohos_association_not_implemented" to "鸿蒙端关联导入待接入",
            "ohos_js_run_not_implemented" to "鸿蒙端 JS 运行待接入",
            // 鸿蒙端 WEB_VIEW 路由 Screen 用到的 key
            "web_view" to "WebView",
            "web_back" to "后退",
            "web_forward" to "前进",
            "ohos_webview_not_implemented" to "WebView 待接入鸿蒙端 @ohos.web.webview",
            // 鸿蒙端 REVIEW_POST 路由 Screen 用到的 key
            "publish_review" to "发布书评",
            "post_review" to "发布"
)
