name: Update Cronet

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # 添加推送权限
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Check Cronet Updates
        run: source .github/scripts/cronet.sh

      - name: Set up JDK 17
        if: ${{ env.cronet == 'ok' }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - uses: gradle/actions/setup-gradle@v4
        if: ${{ env.cronet == 'ok' }}

      - name: Download Cronet
        if: ${{ env.cronet == 'ok' }}
        run: |
          chmod +x gradlew
          ./gradlew app:downloadCronet

      - name: Commit and push changes
        if: ${{ env.cronet == 'ok' }}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: ${{ env.PR_TITLE }}
          file_pattern: |
            *cronet*jar
            *cronet.json
            *updateLog.md
            *gradle.properties
            *cronet-proguard-rules.pro
